"""remove_index_from_genre

Revision ID: 11ce470812c2
Revises: 694a9ed83d63
Create Date: 2025-12-17 03:06:21.717865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ce470812c2'
down_revision: Union[str, Sequence[str], None] = '694a9ed83d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_genre_id'), table_name='books')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_books_genre_id'), 'books', ['genre_id'], unique=False)
    # ### end Alembic commands ###
