"""add_index_to_book_genre

Revision ID: 694a9ed83d63
Revises: c42afadbb4e2
Create Date: 2025-12-15 12:43:32.843774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694a9ed83d63'
down_revision: Union[str, Sequence[str], None] = 'c42afadbb4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_books_genre_id', 'books', ['genre_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_genre_id', table_name='books')
    # ### end Alembic commands ###
