"""add_phone_number

Revision ID: c42afadbb4e2
Revises: 929f9456abda
Create Date: 2025-12-12 10:28:04.368418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42afadbb4e2'
down_revision: Union[str, Sequence[str], None] = '929f9456abda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readers', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readers', 'phone_number')
    # ### end Alembic commands ###
